language: php

matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.0
  - php: hhvm


  allow_failures:
  - php: hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  # Disable xdebug (hhvm doesn't support xdebug)
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi

cache:
  directories:
    - vendor
    - $HOME/.cache/composer

install:
  - travis_retry composer install --no-interaction --prefer-dist


before_script:
  - git reset --hard HEAD
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
