install:
  - travis_retry composer install --no-dev --no-interaction --prefer-source

language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_script:
  - git reset --hard HEAD
  - cp .env.example .env
  - php artisan key:generate
