language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --no-interaction --prefer-source


before_script:
  - git reset --hard HEAD
  - cp .env.example .env
  - php artisan key:generate
